export const actionTypes = {
    LOGIN : 'SIGNIN',
    LOGIN_SUCCESS : "LOGIN_SUCCESS",
    LOGIN_ERROR : 'LOGIN_ERROR',

    SIGNUP : 'SIGNUP',
    SIGNUP_SUCCESS : "SIGNUP_SUCCESS",
    SIGNUP_ERROR : 'SIGNUP_ERROR',

    FATCH_PRODUCTS  : 'FATCH_PRODUCTS',
    FATCH_PRODUCT_DETAILS : 'FATCH_PRODUCT_DETAILS',
    REMOVE_PRODUCT : 'REMOVE_PRODUCT',

    GET_WISHLIST : 'GET_WISHLIST',
    ADD_TO_WISHLIST : 'ADD_TO_WISHLIST',
    REMOVE_FROM_WISHLIST : 'REMOVE_FROM_WISHLIST',

    GET_CART : 'GET_CART',
    ADD_TO_CART : 'ADD_TO_CART',
    REMOVE_FROM_CART : 'REMOVE_FROM_CART',
    INCREASE_QUANTITY : 'INCREASE_QUANTITY',
    DECREASE_QUANTITY : 'DECREASE_QUANTITY'
}