export const actionTypes = {
    LOGIN : 'SIGNIN',
    LOGIN_SUCCESS : "LOGIN_SUCCESS",
    LOGIN_ERROR : 'LOGIN_ERROR',

    SIGNUP : 'SIGNUP',
    SIGNUP_SUCCESS : "SIGNUP_SUCCESS",
    SIGNUP_ERROR : 'SIGNUP_ERROR',

    FATCH_PRODUCTS  : 'FATCH_PRODUCTS',
    FATCH_PRODUCT_DETAILS : 'FATCH_PRODUCT_DETAILS',
    REMOVE_PRODUCT : 'REMOVE_PRODUCT'
}